### PR TITLE
Update rand to 0.7 and only depend on rand-core

### PR DESCRIPTION
**Pull request by est31**
This updates the rand dependency to 0.7. 0.4 is quite outdated and in my crate graph, this crate is the only dependency still using 0.4.

### CODE REVIEW

**Comment by est31** [comment]
CI is broken:
> Service alert: Your project references CircleCI 1.0, or it has no configuration. CircleCI 1.0 and projects without configuration files are no longer supported. You must update your project to use CircleCI 2.0 configuration to continue. Learn more.

**Comment by mscharley** [comment]
Hi there. Thanks for the update! It’s old because I haven’t touched this in several years. It was my one foray into rust. I’ll get to looking at this for you but I’m in the middle of setting up a new computer so it may be a week or two before I get back to it, especially with CI broken.

Glad this was useful to you!

**Comment by est31** [comment]
I'm not using this directly, but [fasthash](https://github.com/flier/rust-fasthash) which uses your library.

**Comment by mscharley** [comment]
@est31 can you merge the latest master please? I've fixed Circle to use v2.

**Comment by mscharley** [comment]
Never mind, this is merged and released as `0.4.0`. Thanks for the update!

**Pull request closed without merging**
